### ISSUE TITLE
Outdated recommendation?

### ISSUE THREAD

**Issue by Evenfire** [preligens-lab/buzzard#3]
Is the [recommendation to use python >= 3.6.7](https://github.com/earthcube-lab/buzzard/blob/master/buzzard/_dataset.py#L1593) still relevant? It dates from Nov 7, 2018 but the changes introduced in https://bugs.python.org/issue34172 were reverted on Dec 6, 2018.

**Comment by Ngoguey42** [comment]
Meh...

Let's remove the recommendation and just keep the url.
