### ISSUE TITLE
Problem with channel indexing while tiling

### ISSUE THREAD

**Issue by ashnair1** [preligens-lab/buzzard#7]
I've been trying to tile a geotiff using buzzard per your README

```
r = buzz.open_raster('path/to/my.tif')

tiles = r.fp.tile((512,512))

for i, fp in enumerate(tiles.flat):
    rgb = r.get_data(fp=fp, channels=(0, 1, 2))
```

However, the following error is thrown `IndexError: too many indices for array: array is 1-dimensional, but 3 were indexed`. 

I checked my tiff and can confirm it has 3 channels

```
>>> r.channel_schema
{'nodata': [None, None, None], 'interpretation': ['redband', 'greenband', 'blueband'], 'offset': [0.0, 0.0, 0.0], 'scale': [1.0, 1.0, 1.0], 'mask': ['all_valid', 'all_valid', 'all_valid']}

```

So I'm not exactly sure why this is happening.

**Comment by ashnair1** [comment]
Found it. Problem was [here](https://github.com/earthcube-lab/buzzard/blob/d0caaaacc366201c6bb970eabe4a2012188f8fc7/buzzard/_tools/parameters.py#L105). Turns out the channels parameter should be a **list** not a tuple. 

```
r = buzz.open_raster('path/to/my.tif')

tiles = r.fp.tile((512,512))

for i, fp in enumerate(tiles.flat):
    rgb = r.get_data(fp=fp, channels=[0, 1, 2]) # channels should be list not tuple
```

**Comment by Ngoguey42** [comment]
Yes. It's fixed here in this PR 
https://github.com/earthcube-lab/buzzard/pull/4/files#diff-6ab378b8ea03234b2848b620f9c10dd20cd95420f592ce35369c514186fd0e9fR102
It should be merge some day!
