### ISSUE TITLE
Issue with adding fields while inserting data

### ISSUE THREAD

**Issue by ashnair1** [preligens-lab/buzzard#8]
I've encountered an error while setting fields to a file that I'm writing to.

```
with buzz.create_vector(path=f'out{suffix}.geojson', type='polygon', driver="GeoJSON", ow=True,
 sr=self.geoim.wkt_virtual).close as out:
        for det in detections:
            out.insert_data(det['geom'], fields={'class': det['class'], 'score': det['score']})
```

Running the above snippet, throws an error as follows:

```
File "/home/ashwin/Desktop/Projects/demo/predictor.py", line 165, in post_process
    out.insert_data(det['geom'], fields={'class': det['class'], 'score': det['score']})
  File "/home/ashwin/anaconda3/envs/rdet/lib/python3.7/site-packages/buzzard/_a_stored_vector.py", line 64, in insert_data
    fields = self._normalize_field_values(fields)
  File "/home/ashwin/anaconda3/envs/rdet/lib/python3.7/site-packages/buzzard/_a_stored_vector.py", line 75, in _normalize_field_values
    i = self._back.index_of_field_name[k]
KeyError: 'class'
```

Source of the error as seen from above trace is [here](https://github.com/earthcube-lab/buzzard/blob/a93081caf857e2d4b2c6b13f059436b224f09a36/buzzard/_a_stored_vector.py#L75).  If the fields I'm setting are not in `self._back.index_of_field_name`, setting will fail. 

I'm not sure why this is the case. Is this not the correct way to set fields for a vector file? What exactly is `self._back` and what does it have to do with the fields I'm setting?

**Comment by Ngoguey42** [comment]
`class` and `score` are missing from `index_of_field_name` because you didn't define the fields when you created your file. Add something like `fields=[{'name': 'class', 'type': str}, {'name': 'score', 'type': float}]` to `create_vector`.

The `back` object is explained in https://buzzard.readthedocs.io/en/latest/faq_and_caveats.html

**Comment by ashnair1** [comment]
That was it. Thanks
